name: cooquoi
services:
  cooquoi_db:
    image: postgis/postgis:16-3.4
    container_name: cooquoi-admin-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_POSTGRES_USERNAME:-cooquoiuser}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD:-cooquoipassword}
      POSTGRES_DB: ${DB_POSTGRES_DB_NAME:-cooquoi}
    volumes:
      - cooquoi_db_data:/var/lib/postgresql/data
      - ../../scripts/init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql:ro

volumes:
  cooquoi_db_data:
